# Generated by Django 3.0 on 2019-12-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191202_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=140, unique=True, verbose_name='E-mail'),
        ),
    ]
