# Generated by Django 3.0 on 2019-12-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Produto')),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Fornecedor')),
            ],
        ),
    ]
